#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'surfaceArea' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY A as parameter.
#

def surfaceArea(A):
    # Write your code here
    n = len(A)
    m = len(A[0])
    B = [[0] * m] + A
    B.append([0] * m)
    for item in B:
        item.append(0)
        item.insert(0, 0)
    rez = 0
    for i in range(n + 1):
        for j in range(m + 1):
            rez += abs(B[i][j] - B[i + 1][j])
            rez += abs(B[i][j] - B[i][j + 1])
    return rez + 2 * m * n

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    H = int(first_multiple_input[0])

    W = int(first_multiple_input[1])

    A = []

    for _ in range(H):
        A.append(list(map(int, input().rstrip().split())))

    result = surfaceArea(A)

    fptr.write(str(result) + '\n')

    fptr.close()
