#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'formingMagicSquare' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY s as parameter.
#

def compare_lists(list1, list2):
    sum_of_differences = 0
    for i in range(len(list1)):
        sum_of_differences += abs(list1[i] - list2[i])
    return sum_of_differences

def formingMagicSquare(s):
    # Write your code here
    l1 = [6, 1, 8, 7, 5, 3, 2, 9, 4]
    l2 = [8, 1, 6, 3, 5, 7, 4, 9, 2]
    l3 = [6, 7, 2, 1, 5, 9, 8, 3, 4]
    l4 = [8, 3, 4, 1, 5, 9, 6, 7, 2]
    l5 = [2, 7, 6, 9, 5, 1, 4, 3, 8]
    l6 = [4, 3, 8, 9, 5, 1, 2, 7, 6]
    l7 = [2, 9, 4, 7, 5, 3, 6, 1, 8]
    l8 = [4, 9, 2, 3, 5, 7, 8, 1, 6] 
    td = []
    lf = []
    for i in s:
        for j in i:
            lf.append(j)
    for i in [l1,l2,l3,l4,l5,l6,l7,l8]:
        td.append(compare_lists(i,lf))
    return min(td)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = []

    for _ in range(3):
        s.append(list(map(int, input().rstrip().split())))

    result = formingMagicSquare(s)

    fptr.write(str(result) + '\n')

    fptr.close()
