#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'workbook' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER k
#  3. INTEGER_ARRAY arr
#

def workbook(n, k, arr):
    # Write your code here
    specials = {}
    chap_page = []
    pages = 0
    for i in range(n):
        prob_page = {}
        for j in range(arr[i]):
            prob_page[j+1] = pages + j//k + 1
        chap_page.append(prob_page)
        pages += arr[i]//k + (0 if arr[i]%k == 0 else 1)
    for dic in chap_page:
        for x,y in dic.items():
            if x == y:
                specials[x] = y
    return len(specials)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = workbook(n, k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
