#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    control = {}
    a.sort()
    for i in range(len(a)):
        temp = []
        for j in range(i, len(a)):
            if abs(a[i] - a[j]) <= 1:
                temp.append(a[j])
        control.setdefault(a[i], temp)
    length = [len(value) for key, value in control.items()]
    return max(length)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
