#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'strangeCounter' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts LONG_INTEGER t as parameter.
#

#written the code to import floor and log from math module
from math import floor,log

def strangeCounter(t):
    # Write your code here
    k = floor(log((t + 2)/3)/log(2)) 
    return 6 * (2**k) - 2 - t
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    result = strangeCounter(t)

    fptr.write(str(result) + '\n')

    fptr.close()
