#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bomberMan' function below.
#
# The function is expected to return a STRING_ARRAY.
# The function accepts following parameters:
#  1. INTEGER n
#  2. STRING_ARRAY grid
#

#written the code here too for the grid
def bombs_list(grid):
    bombs = []
    for i,x in enumerate(grid):        
        bombs.extend([(i, m.start(0)) for m in re.finditer(chr(79), x)])
    return bombs

def bomberMan(n, grid):
    # Write your code here
    if n == 1:
        return grid
        
    full_row = chr(79) * len(grid[0])
    full_grid = [full_row] * len(grid)
        
    if n % 2 == 0:        
        return full_grid
             
    bombs = bombs_list(grid)
    for _ in range(2):        
        gb = full_grid.copy()        
        for j in bombs:
            if j[0]-1 >= 0:                
                gb[j[0]-1] = gb[j[0]-1][:j[1]] + '.' + gb[j[0]-1][j[1]+1:]
            if j[0]+1 < len(grid):                
                gb[j[0]+1] = gb[j[0]+1][:j[1]] + '.' + gb[j[0]+1][j[1]+1:]
            if j[1]+1 < len(grid[0]):                
                gb[j[0]] = gb[j[0]][:j[1]+1] + '.' + gb[j[0]][j[1]+2:]
            if j[1]-1 >= 0:                
                gb[j[0]] = gb[j[0]][:j[1]-1] + '.' + gb[j[0]][j[1]:]
            gb[j[0]] = gb[j[0]][:j[1]] + '.' + gb[j[0]][j[1]+1:]
        if n == 3 or (n-3)%4 == 0:
            return gb
        bombs = bombs_list(gb)          
    return gb

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    r = int(first_multiple_input[0])

    c = int(first_multiple_input[1])

    n = int(first_multiple_input[2])

    grid = []

    for _ in range(r):
        grid_item = input()
        grid.append(grid_item)

    result = bomberMan(n, grid)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
